language: python
notifications:
  email: false
python:
  - "2.6"
  - "2.7"
install:
  - "easy_install -U setuptools"
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script:
  - py.test test/test_bigtrees.py --doctest-modules -v --cov bigtrees --cov-report term-missing
after_success:
  - coveralls
